### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by cgivre** [k255/drill-fuzzy-search#1]
I'm a bit of a n00b, so I apologize for the question, but I'm having trouble getting this to build correctly.  I'm using a Mac, with Maven 3.39, Java 1.8.0_65.  
I followed your instructions to build the plugin and copied it to the drill jars/3rdParty directory.  I also built Simmetrics (https://github.com/Simmetrics/simmetrics), and copied that to the Drill directory. 
However, when I try to execute a query, I get the following error:

```
: jdbc:drill:zk=local> select columns[0] as textA, columns[1] as textB, 
. . . . . . . . . . . >     levenshtein(columns[0], columns[1]) as distance
. . . . . . . . . . . >     from cp.`sample-data/similarities.csv`;
Error: SYSTEM ERROR: CompileException: Line 118, Column 17: Unknown variable or type "org.simmetrics.StringMetrics"

Fragment 0:0

[Error Id: 2aa0798f-b2cf-4a17-963c-dff36a59ca49 on 10.241.7.26:31010] (state=,code=0)

```

I think the issue is that the version of Simmetrics is not correct, but I'm not sure.  Do you have any suggestions?  Also, like I said, I'm a n00b, but when you build the drill-fuzzy-functions, should maven pull back the Simmetrics and build that automatically or is that something you have to do by yourself?
Thanks,

**Comment by k255** [comment]
Please try downloading simmetric dependency directly from [maven repository](http://central.maven.org/maven2/com/github/mpkorstanje/simmetrics-core/3.2.3/simmetrics-core-3.2.3.jar) and then copy it to drills' 3rdParty directory.
I've updated drill version in pom.xml from 1.2.0-Snapshot to 1.3.0 to make the build bit easier. Also installation instructions are now updated with link to simmetric dependency download.

I've just built the plugin and tried it with drill 1.7.0 - it works just fine.
Let me know if it helps!

**Comment by cgivre** [comment]
That did the trick.  Thank you very much!

BTW, I'm going to put a list of drill UDFs, plus some I've been working on
on my blog.

**Comment by k255** [comment]
Good to hear! Don't forget to star if you like it!
